class HeaderLocators:
    INFOLINE = ".app-header__top-text"
    INFOLINE_CLOSE = ".app-header_close-button"
    CATALOG = ".app-header-btn.app-hamburger-btn:has-text('Каталог')"
    STORES_HEADER = ".app-header-btn:has-text('Магазины')"
    LOCATION_HEADER = ".app-header__select-city-btn"
    LOGO = ".logo-desktop"
    SEARCH = ".search-lupa-btn"
    SEARCH_FIELD = "#header-search-input"
    SEARCH_CLOSE = ".search-cross-btn"
    SEARCH_SUBMIT_BTN = ".search-lupa-fake"
    SEARCH_POPULAR = ".app-desktop-search__popup-link"
    PROFILE_HEADER = ".js-profile-open"
    FAVORITES = "#ico-favorites"
    CART_HEADER = "a[data-basket$='/personal/cart/']"
